import {useEffect,useRef,useState} from 'react';
import {X,Save} from 'lucide-react';
import {projectPanorama} from './panorama';
import {frameRatio} from './compositionNodes';
type View={yaw:number;pitch:number;fov:number;ratio?:string};
export function PanoramaViewer({asset,onSave,onClose,projectRatio='16:9',initialView,onViewChange}:{
 asset:{url:string;name:string};onSave:(blob:Blob,name:string)=>Promise<void>;onClose:()=>void;projectRatio?:string;initialView?:Partial<View>;onViewChange?:(view:View)=>void;
}) {
 const [view,setView]=useState<View>({yaw:0,pitch:0,fov:90,...initialView});
 const {yaw,pitch,fov}=view,ratio=frameRatio(view.ratio || projectRatio);
 const [source,setSource]=useState<ImageData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const canvas=useRef<HTMLCanvasElement>(null),drag=useRef<{x:number;y:number;yaw:number;pitch:number}|null>(null);
 function patch(value:Partial<View>){const next={...view,...value};setView(next);onViewChange?.(next);}
 useEffect(()=>{let active=true;setSource(null);setError('');const image=new Image();image.onload=()=>{if(!active)return;try{
   if(Math.abs(image.width/image.height-2)>.04)throw new Error('请选择 2:1 等距柱状全景图，普通照片不能正确进行全景取景。');
   const c=document.createElement('canvas');c.width=Math.min(4096,image.width);c.height=Math.round(image.height*c.width/image.width);const ctx=c.getContext('2d')!;ctx.drawImage(image,0,0,c.width,c.height);setSource(ctx.getImageData(0,0,c.width,c.height));
 }catch(e:any){setError(e.message || '全景图读取失败')}};image.onerror=()=>setError('无法加载图片');image.src=asset.url;return()=>{active=false}},[asset.url]);
 useEffect(()=>{if(!source||!canvas.current)return;const target=canvas.current;target.width=ratio>=1?640:Math.round(640*ratio);target.height=ratio>=1?Math.round(640/ratio):640;target.getContext('2d')!.putImageData(new ImageData(projectPanorama(source,target.width,target.height,fov,yaw,pitch),target.width,target.height),0,0)},[source,yaw,pitch,fov,ratio]);
 async function save(){if(!source)return;setBusy(true);try{const target=document.createElement('canvas');target.width=ratio>=1?1280:Math.round(1280*ratio);target.height=ratio>=1?Math.round(1280/ratio):1280;target.getContext('2d')!.putImageData(new ImageData(projectPanorama(source,target.width,target.height,fov,yaw,pitch),target.width,target.height),0,0);const blob=await new Promise<Blob>((resolve,reject)=>target.toBlob(b=>b?resolve(b):reject(new Error('图片编码失败')),'image/png'));await onSave(blob,`全景构图_${Math.round(yaw)}_${Math.round(pitch)}.png`);onClose()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <div className="modal-overlay"><div className="panorama-modal" role="dialog" aria-modal="true" aria-label="全景取景"><div className="panel-title"><h2>全景取景 · {asset.name}</h2><button className="icon-button" disabled={busy} onClick={onClose} aria-label="关闭全景"><X/></button></div><p className="muted">拖动画面选择方向，保存为普通构图参考图。</p>{error&&<p className="error">{error}</p>}<canvas ref={canvas} style={{touchAction:'none',cursor:'grab',maxHeight:'50vh',objectFit:'contain'}} onPointerDown={e=>{if(busy)return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,yaw,pitch}}} onPointerMove={e=>{if(!drag.current||busy)return;patch({yaw:((drag.current.yaw-(e.clientX-drag.current.x)*.25+540)%360)-180,pitch:Math.max(-85,Math.min(85,drag.current.pitch+(e.clientY-drag.current.y)*.25))})}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}/><fieldset disabled={busy} className="two-fields"><label>方向 {Math.round(yaw)}°<input type="range" min="-180" max="180" value={yaw} onChange={e=>patch({yaw:Number(e.target.value)})}/></label><label>俯仰 {Math.round(pitch)}°<input type="range" min="-85" max="85" value={pitch} onChange={e=>patch({pitch:Number(e.target.value)})}/></label><label>水平视角 {fov}°<input type="range" min="30" max="120" value={fov} onChange={e=>patch({fov:Number(e.target.value)})}/></label><label>画幅<select value={view.ratio || ''} onChange={e=>patch({ratio:e.target.value})}><option value="">跟随项目 · {projectRatio}</option>{['21:9','16:9','4:3','1:1','3:4','9:16'].map(value=><option key={value}>{value}</option>)}</select></label></fieldset><button className="primary" disabled={!source||busy} onClick={save}><Save size={16}/>{busy?'保存中':'保存构图参考图'}</button></div></div>;
}
