import {useEffect,useRef,useState} from 'react';
import {X,Save} from 'lucide-react';
import {projectPanorama} from './panorama';
export function PanoramaViewer({asset,onSave,onClose}:{asset:{url:string;name:string};onSave:(blob:Blob,name:string)=>Promise<void>;onClose:()=>void}){
 const [yaw,setYaw]=useState(0),[pitch,setPitch]=useState(0),[fov,setFov]=useState(90),[ratio,setRatio]=useState(16/9),[source,setSource]=useState<ImageData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const canvas=useRef<HTMLCanvasElement>(null),drag=useRef<{x:number;y:number;yaw:number;pitch:number}|null>(null);
 useEffect(()=>{let active=true;const image=new Image();image.onload=()=>{if(!active)return;try{const c=document.createElement('canvas');c.width=Math.min(4096,image.width);c.height=Math.round(image.height*c.width/image.width);const ctx=c.getContext('2d')!;ctx.drawImage(image,0,0,c.width,c.height);setSource(ctx.getImageData(0,0,c.width,c.height))}catch{setError('全景图读取失败')}};image.onerror=()=>setError('无法加载图片');image.src=asset.url;return()=>{active=false}},[asset.url]);
 useEffect(()=>{if(!source||!canvas.current)return;const target=canvas.current;target.width=640;target.height=Math.round(640/ratio);target.getContext('2d')!.putImageData(new ImageData(projectPanorama(source,target.width,target.height,fov,yaw,pitch),target.width,target.height),0,0)},[source,yaw,pitch,fov,ratio]);
 async function save(){if(!source)return;setBusy(true);try{const target=document.createElement('canvas');target.width=1280;target.height=Math.round(1280/ratio);target.getContext('2d')!.putImageData(new ImageData(projectPanorama(source,target.width,target.height,fov,yaw,pitch),target.width,target.height),0,0);const blob=await new Promise<Blob>((resolve,reject)=>target.toBlob(b=>b?resolve(b):reject(new Error('图片编码失败')),'image/png'));await onSave(blob,`全景构图_${Math.round(yaw)}_${Math.round(pitch)}.png`);onClose()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <div className="modal-overlay"><div className="panorama-modal" role="dialog" aria-modal="true" aria-label="全景构图"><div className="panel-title"><h2>全景构图 · {asset.name}</h2><button className="icon-button" onClick={onClose} aria-label="关闭全景"><X/></button></div><p className="muted">适用于 2:1 等距柱状全景图。拖动画面改变朝向，保存的透视图可用于生成节点。</p>{error&&<p className="error">{error}</p>}<canvas ref={canvas} style={{touchAction:'none',cursor:'grab'}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,yaw,pitch}}} onPointerMove={e=>{if(!drag.current)return;setYaw(((drag.current.yaw-(e.clientX-drag.current.x)*.25+540)%360)-180);setPitch(Math.max(-85,Math.min(85,drag.current.pitch+(e.clientY-drag.current.y)*.25)))}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}/><div className="two-fields"><label>方向 {Math.round(yaw)}°<input type="range" min="-180" max="180" value={yaw} onChange={e=>setYaw(Number(e.target.value))}/></label><label>俯仰 {Math.round(pitch)}°<input type="range" min="-85" max="85" value={pitch} onChange={e=>setPitch(Number(e.target.value))}/></label><label>水平视角 {fov}°<input type="range" min="30" max="120" value={fov} onChange={e=>setFov(Number(e.target.value))}/></label><label>画幅<select value={ratio} onChange={e=>setRatio(Number(e.target.value))}><option value={16/9}>16:9</option><option value={1}>1:1</option><option value={9/16}>9:16</option></select></label></div><button className="primary" disabled={!source||busy} onClick={save}><Save size={16}/>{busy?'保存中':'保存构图到素材库'}</button></div></div>;
}
